# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 16:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='textual_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 0, 17, 31, 122096)),
        ),
    ]
